### PR TITLE
Remove `TimeoutCancellationException` from `Publisher.stop`

### LINKED ISSUE #862: Sending presence leave event times out whilst still connected
When a delivery has completed, the publisher sends a presence leave event on the tracking channel and then detaches from the channel.

This is typically visible in the logs as “`zo0.b: leave();`” followed by “`io.ably.lib.transport.b: onMessage()`” with the returned ACK, for example:

```
18-12-22 19:59:07.702: zo0.b: leave(); channel = tracking:bo:22606154
18-12-22 19:59:07.702: zo0.b: update(); channel = tracking:bo:22606154
18-12-22 19:59:07.703: io.ably.lib.transport.WebSocketTransport: send(); action = presence
18-12-22 19:59:07.703: io.ably.lib.transport.WebSocketTransport: send(): presence: {"action":14,"channel":"tracking:bo:22606154","count":0,"flags":0,"msgSerial":339,"presence":[{"data":"{\"rawLocations\":false,\"type\":\"PUBLISHER\"}","action":3}],"timestamp":0}
18-12-22 19:59:07.923: io.ably.lib.transport.b: onMessage() ( ... ): ack: {"action":1,"count":1,"flags":0,"msgSerial":339,"timestamp":0}
```

From log redacted_08147607dc6202d1cb65ef57cdc42d53_error_session_639FA682023000012C9EE2B941CCBE13_DNE_1_v2.log however, the leave event was sent but no ACK was received:

```
18-12-22 19:48:58.570: zo0.b: leave(); channel = tracking:bo:22607777
18-12-22 19:48:58.571: zo0.b: update(); channel = tracking:bo:22607777
18-12-22 19:48:58.572: io.ably.lib.transport.WebSocketTransport: send(); action = presence
18-12-22 19:48:58.589: io.ably.lib.transport.WebSocketTransport: send(): presence: {"action":14,"channel":"tracking:bo:22607777","count":0,"flags":0,"msgSerial":1,"presence":[{"data":"{\"rawLocations\":false,\"type\":\"PUBLISHER\"}","action":3}],"timestamp":0}
18-12-22 19:49:27.032: [j] Publisher stop operation failed kotlinx.coroutines.c3: Timed out waiting for 30000 ms 	at kotlinx.coroutines.e3.a(Unknown Source:24) 	at kotlinx.coroutines.d3.run(Unknown Source:2) 	at kotlinx.coroutines.l1$b.run(Unknown Source:2) 	at kotlinx.coroutines.l1.s0(SourceFile:76) 	at kotlinx.coroutines.t0.run(SourceFile:43) 	at java.lang.Thread.run(Thread.java:923)
```

This resulted in a “Stopping Publisher Failed” exception:

```
PublisherStoppedError(message=Stopping Publisher Failed, cause=kotlinx.coroutines.c3: Timed out waiting for 30000 ms) 	at redacted.ably.PublisherService$h.invokeSuspend(SourceFile:67) 	at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:12) 	at kotlinx.coroutines.b1.run(SourceFile:105) 	at android.os.Handler.handleCallback(Handler.java:938) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:246) 	at android.app.ActivityThread.main(ActivityThread.java:8645) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) Caused by: kotlinx.coroutines.c3: Timed out waiting for 30000 ms 	at kotlinx.coroutines.e3.a(Unknown Source:24) 	at kotlinx.coroutines.d3.run(Unknown Source:2) 	at kotlinx.coroutines.l1$b.run(Unknown Source:2) 	at kotlinx.coroutines.l1.s0(SourceFile:76) 	at kotlinx.coroutines.t0.run(SourceFile:43) 	at java.lang.Thread.run(Thread.java:923)
```

Looking in the router logs, the client was connected at the time the presence leave event was sent (they were connected to ap-southeast-2 between 2022-12-18T23:48:41.067Z and 2022-12-18T23:49:56.073Z, the above logs are 4 hours behind UTC).

The SDK agent string was: `ably-java/1.2.20 ably-asset-tracking-android/1.5.1 android/30`

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
## Background

It’s not clear for callers of `Publisher.stop` what it means if it throws `TimeoutCancellationException`, or how they should respond to it. For example, do they need to try calling it again, or is the publisher now in some terminal broken state?

(The same questions also apply if the publisher throws `ConnectionException`; I’ve created #873 for addressing this.)

## What’s changed

This comes from the change suggested by @lmars in https://github.com/ably/ably-asset-tracking-android/issues/862#issuecomment-1366083580. 

We remove the operation-wide timeout parameter, and instead expose a parameter to give the caller control over only the presence leave operation.

We explain what will happen if this timeout elapses and how this affects the publisher’s online status from the point of view of subscribers.

## API considerations

From 944d88461cb36318032136adcf3b085c8e4da3d9:

> This is technically a breaking change to the publisher SDK API, both in terms of semantics and parameter name. I’ll start a discussion on the pull request to decide how we want to address this, and then update this commit message.

My change to `UPDATING.md` anticipates this just being a minor version bump. Do we think this warrants a major version bump?

## Reviewing

Please review commit-by-commit.

## Issues closed

Closes #862.

### CODE REVIEW

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt [hunk 1]
```diff
@@ -119,13 +118,12 @@ interface Publisher {
      * Stops this publisher from publishing locations. Once a publisher has been stopped, it cannot be restarted.
      * Please note that calling this method will remove the notification provided by [Builder.backgroundTrackingNotificationProvider].
      *
-     * @param timeoutInMilliseconds After this duration the stopping procedure will be canceled. Default value is 30 seconds.
+     * @param presenceLeaveTimeoutInMilliseconds After this duration, the attempt to leave the Ably channel presence will be cancelled. If this timeout elapses, the remainder of the stopping procedure will still be performed, and subscribers will see the publisher go offline within 75 seconds. Default value is 30 seconds.
```
Comment (KacperKluka) [inline publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt:121]: The same thing about those `75 seconds` as before 😉

**Review by KacperKluka — COMMENTED** [review]
Overall looks good, just one thing to clarify 😉

**Review by davyskiba — APPROVED** [review]

File: UPDATING.md [hunk 2]
```diff
@@ -1,5 +1,13 @@
 # Upgrade / Migration Guide
 
+## Version 1.5.1 to 1.6.0
+
+### Changed timeout behaviour of `Publisher.stop`
+
+It is no longer possible to specify a timeout for the entire `Publisher.stop` operation. The `timeoutInMilliseconds` parameter has been replaced by a `presenceLeaveTimeoutInMilliseconds` parameter, which allows you to specify a timeout for part of this operation.
+
+The `Publisher.stop` method now no longer throws `TimeoutCancellationException`, and guarantees that subscribers will see the publisher go offline within 75 seconds of this method returning.
```
[the remark this answers is not in the document]
Comment (lawrence-forooghian) [reply UPDATING.md]: Good point! I've updated the documentation, and also updated it to make it consistent with the other (to talk about how long it may take for subscribers to see the publisher go offline starting from the moment the method is called instead of the moment it returns).

File: common/src/main/java/com/ably/tracking/common/Ably.kt [hunk 3]
```diff
@@ -224,10 +224,15 @@ interface Ably {
...
...t will still call [AblySdkRealtime.close] on the underlying Realtime object. As described by [RTN12](https://sdk.ably.com/builds/ably/specification/main/features/#RTN12), this means that whatever state the Realtime object is currently in, it will no longer attempt to connect to Ably. If the call to [AblySdkRealtime.close] is successful, then the client will have immediately left presence (see [the presence documentation](https://ably.com/docs/realtime/presence?lang=javascript#unstable-connections) which says "If a client calls `leave()` or `close()` they immediately send a `leave` event."). If there are network issues that prevent the call to [AblySdkRealtime.close] from succeeding, then the server will after around 60 seconds consider the client to have disconnected and 15 seconds after that will synthesize a presence leave event (see mention of “abrupt disconnect“ on the aforementioned documentation). The data of this presence leave event will be the same as the last presence data published for that member – this behaviour is not officially documented but is confirmed in [this GitHub comment](https://github.com/ably/ably-asset-tracking-android/issues/862#issuecomment-1366958096).
```
[the remark this answers is not in the document]
Comment (lawrence-forooghian) [reply common/src/main/java/com/ably/tracking/common/Ably.kt]: Updated, thanks!

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt (hunk 1 above)
Comment (lawrence-forooghian) [reply publishing-sdk/src/main/java/com/ably/tracking/publisher/Publisher.kt]: Good point! I've updated the documentation, and also updated it to make it consistent with the rest (to talk about how long it may take for subscribers to see the publisher go offline starting from the moment the method is called instead of the moment it returns).

**Review by KacperKluka — APPROVED** [review]
LGTM 👍

**Comment by lawrence-forooghian** [comment]
@KacperKluka @davyskiba did you have any thoughts about what kind of version bump this necessitates (perhaps Kacper you have an idea of how we've handled this sort of thing in the past)? (See "API considerations" in the description.)

**Comment by KacperKluka** [comment]
@lawrence-forooghian IMO this particular API situation is debatable as you only change a parameter name, so this only affects users that use the named parameters in functions. Due to this I'd be fine with either bumping the minor number or bumping the major one 😉

**Review by paddybyers — APPROVED** [review]
I've look at your reasoning in the comments and I'm happy to approve that approach. I haven't reviewed the code itself or the tests.

**Comment by QuintinWillison** [comment]
@lawrence-forooghian @KacperKluka I've had a look at the proposed change to the `stop` method (being the rename of the `Long` argument from `timeoutInMilliseconds` to `presenceLeaveTimeoutInMilliseconds`).

I don't believe it's correct to summarise the impact of this change as "only affects users that use the named parameters in functions": If a user doesn't use named parameters when calling this method but does pass a value to override this argument's default value then that value will now be interpreted in a different way, resulting in a change in SDK behaviour, regardless of the name.

Therefore, I think the change as currently presented is a breaking / incompatible change (`major`) whichever way we look at it.

A couple of alternative routes spring to mind that might make this easier to explain to customers when we do a release (migration guide, etc..):

1. Change the argument type entirely, perhaps something like a `StopOptions` data class that has a `presenceLeaveTimeoutInMilliseconds` member.
2. Use deprecation and allow the timeout value to be optionally injected elsewhere:
    - For the current `stop(Long = 30_000L)` method, leave the argument in place, remove the default value and deprecate it -- it becomes `stop(Long)` (deprecated)
    - add a new overload for `stop()` that takes no arguments
    - add a builder method to allow users to inject this new timeout value before they even start the publisher -- I'm pretty sure they'll know this up front, right?

Option 1 is definitely a breaking change (`major`), but option 2 could be a new feature / enhancement (`minor`).
My preference would be option 2.

**Comment by jaley** [comment]
@lawrence-forooghian (or maybe @paddybyers or @lmars) - does the user really *need* control over this presence leave timeout? It looks a bit odd to me, as Ably presence functionality isn't really exposed to the user elsewhere in the API, it's more of implementation strategy for delivering the required experience, AFAICT? If there's no strong reason to expose the presence leave timeout, would it not be better to just do part of @QuintinWillison's suggestion (2) above:

* Add a new `stop()` overload that takes no parameters
* Deprecate `stop(Long)` and just document that the timeout parameter is now ignored and we won't throw that exception.

This isn't source-breaking, and the only behaviour change is that we'll no-longer throw an exception, which has already been agreed as an improvement from the user perspective?

**Comment by paddybyers** [comment]
>  does the user really need control over this presence leave timeout?

I don't think so.

> would it not be better to just do part of @QuintinWillison's suggestion (2) above:

- Add a new stop() overload that takes no parameters
- Deprecate stop(Long) and just document that the timeout parameter is now ignored and we won't throw that exception.

I'm ok with that

**Comment by lawrence-forooghian** [comment]
Before I go ahead with deprecating the ability to control the duration of the publisher `stop()` method call, I'd like to be sure that we're not removing something the client is depending on. @KacperKluka do you remember what the original motivation was for adding that timeout parameter? Was it based on some user need?

**Comment by KacperKluka** [comment]
> do you remember what the original motivation was for adding that timeout parameter

I don't remember this exactly but I think we simply wanted to avoid freezing the SDK as the `stop` method is going to block the internal worker queue in order to correctly perform the stop operation 🤔 As far as I remember it wasn't a request from a customer but rather our idea 😉

File: subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StopConnectionWorker.kt [hunk 4]
```diff
@@ -22,7 +22,7 @@ internal class StopConnectionWorker(
         // We're using [runBlocking] on purpose as we want to block the whole subscriber when it's stopping.
         runBlocking {
             try {
-                ably.close(properties.presenceData)
+                ably.close(properties.presenceData, presenceLeaveTimeoutInMilliseconds = null)
```
Comment (davyskiba) [inline subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StopConnectionWorker.kt:25]: What is the reasoning behind treating subscriber stop differently?

**Comment by jaley** [comment]
> deprecating the ability to control the duration of the publisher stop() method call, I'd like to be sure that we're not removing something the client is depending on.

This is a fair point. Another option then would actually be to leave the function signature as it is, honour the timeout but not throw an exception if it expires, simply give up and stop blocking the caller. Was that option considered? (Sorry, I may have missed earlier discussion)

File: subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StopConnectionWorker.kt (hunk 4 above)
Comment (lawrence-forooghian) [reply subscribing-sdk/src/main/java/com/ably/tracking/subscriber/workerqueue/workers/StopConnectionWorker.kt:25]: I don't know – this operation previously had no timeout and so that's the behaviour I’ve preserved.

**Comment by lawrence-forooghian** [comment]
If we believe that having any sort of timeout on `stop` is a mistake, should we just remove the argument from that method, increase the major version and call it a day? Any other kind of change (ignoring the parameter, not throwing an exception etc) is all, technically, a breaking change to the API.

**Comment by lawrence-forooghian** [comment]
As agreed in our call this morning, I’ve removed the timeout logic and removed the corresponding parameter on `stop()`. I've written a bit about this decision in the commit message.

I’ve updated the `UPDATING.md` to explain how users can replace the timeout by using Kotlin’s `withTimeout`.

@KacperKluka @davyskiba I've added a couple of tests to give me confidence that if a user calls `stop()` from within a `withTimeout` block then the `TimeoutCancellationException` does indeed reach the user. I think that they probably come from my poor knowledge of Kotlin coroutines, so if you think them unnecessary please let me know and I'll get rid of them.

File: publishing-sdk/src/test/java/com/ably/tracking/publisher/DefaultPublisherTest.kt [hunk 5]
```diff
@@ -221,4 +225,35 @@ class DefaultPublisherTest {
...
+        }
+
+        // Then...
+        coVerify(exactly = 1) {
+            // ...ably.close() is called...
+            ably.close(any())
+        }
+
+        // ...and the withTimeout block throws a TimeoutCancellationException.
+        Assert.assertTrue(caughtTimeoutCancellationException)
```
Comment (davyskiba) [inline publishing-sdk/src/test/java/com/ably/tracking/publisher/DefaultPublisherTest.kt:255]: Please use [Expectations](https://github.com/ably/ably-asset-tracking-android/blob/main/android-test-common/src/main/java/com/ably/tracking/test/android/common/Expectations.kt) instead of assertions here

Comment (lawrence-forooghian) [reply publishing-sdk/src/test/java/com/ably/tracking/publisher/DefaultPublisherTest.kt:255]: Happy to change it, but would you mind explaining why? It seems like the main functionality of the `Expectation` class is to provide the ability to wait for some asynchronous operation to complete. But we're already waiting for the coroutine call to complete by using `runBlocking`.

Comment (davyskiba) [reply publishing-sdk/src/test/java/com/ably/tracking/publisher/DefaultPublisherTest.kt:255]: Right await is not needed here, I would use it here mostly for a more verbose messages when the test fails

Comment (lawrence-forooghian) [reply publishing-sdk/src/test/java/com/ably/tracking/publisher/DefaultPublisherTest.kt:255]: Does that mean we can stick to using assert, or is there some other reason to switch to using expectations?

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/StopWorker.kt [hunk 6]
```diff
@@ -26,19 +24,16 @@ internal class StopWorker(
...
+                if (properties.isTracking) {
+                    publisherInteractor.stopLocationUpdates(properties)
                 }
+                publisherInteractor.closeMapbox()
+                ably.close(properties.presenceData)
+                properties.dispose()
+                callbackFunction(Result.success(Unit))
             } catch (exception: ConnectionException) {
                 callbackFunction(Result.failure(exception))
             } catch (exception: TimeoutCancellationException) {
```
Comment (KacperKluka) [inline publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/StopWorker.kt:39]: Since the `withTimeout` block is removed I think we no longer need to catch the `TimeoutCancellationException` 🤔

**Review by KacperKluka — CHANGES_REQUESTED** [review]
Looks good, just a few small things to improve 😉

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/DefaultPublisher.kt [hunk 7]
```diff
@@ -112,6 +111,14 @@ constructor(
         }
     }
 
+    @Deprecated(
+        "The timeoutInMilliseconds parameter is now ignored and should not be used.",
+        replaceWith = ReplaceWith("stop()")
+    )
+    override suspend fun stop(timeoutInMilliseconds: Long) {
+        stop()
+    }
```
[the remark this answers is not in the document]
Comment (lawrence-forooghian) [reply publishing-sdk/src/main/java/com/ably/tracking/publisher/DefaultPublisher.kt:120]: I added it because Android Studio was giving me this warning:

image

Should I ignore the warning, or keep it as it currently is, or suppress the warning in some other way?

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/StopWorker.kt (hunk 6 above)
Comment (lawrence-forooghian) [reply publishing-sdk/src/main/java/com/ably/tracking/publisher/workerqueue/workers/StopWorker.kt:39]: Good point, removed.

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/DefaultPublisher.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (lawrence-forooghian) [reply publishing-sdk/src/main/java/com/ably/tracking/publisher/DefaultPublisher.kt]: (I just tried removing it, and it actually seems to be a build error, not just a warning - try running `./gradlew check` to reproduce.)

[the remark this answers is not in the document]
Comment (KacperKluka) [reply publishing-sdk/src/main/java/com/ably/tracking/publisher/DefaultPublisher.kt:120]: Oh sorry, this must be my mistake, I was recently deprecating some things in AAT but they were regular methods, not an interface-implementation pairs 😅 It looks like in this situation the `@Deprecated` annotation needs to be added in both places 👍 Sorry for the trouble 😉

**Review by KacperKluka — APPROVED** [review]
Good job! LGTM 👍

File: publishing-sdk/src/test/java/com/ably/tracking/publisher/DefaultPublisherTest.kt (hunk 5 above)
Comment (davyskiba) [reply publishing-sdk/src/test/java/com/ably/tracking/publisher/DefaultPublisherTest.kt:255]: Yes, we can :)
I prefer to use something with a more informative error message here, like Expectation or Truth fluent assertion, but it is not worth keeping this pr open longer just for that
