### PR TITLE
Fix memory leak issue

### LINKED ISSUE #810: Memory leak connected to the Mapbox SDK
We've got informed about a memory leak when using the Publisher SDK. We should investigate whether that's AAT or Mapbox issue. Below you can find the error log with all private information removed.

```
┬───
│ GC Root: Global variable in native code
│
├─ com.mapbox.navigation.core.accounts.
│  BillingController$$ExternalSyntheticLambda2 instance
│    Leaking: UNKNOWN
│    Retaining 14.6 kB in 559 objects
│    ↓ BillingController$$ExternalSyntheticLambda2.f$0
│                                                  ~~~
├─ com.mapbox.navigation.core.accounts.BillingController instance
│    Leaking: UNKNOWN
│    Retaining 14.6 kB in 558 objects
│    ↓ BillingController.tripSession
│                        ~~~~~~~~~~~
├─ com.mapbox.navigation.core.trip.session.MapboxTripSession instance
│    Leaking: UNKNOWN
│    Retaining 14.4 kB in 543 objects
│    ↓ MapboxTripSession.tripService
│                        ~~~~~~~~~~~
├─ com.mapbox.navigation.core.trip.service.MapboxTripService instance
│    Leaking: UNKNOWN
│    Retaining 12.7 kB in 449 objects
│    ↓ MapboxTripService.tripNotification
│                        ~~~~~~~~~~~~~~~~
├─ com.ably.tracking.publisher.MapboxTripNotification instance
│    Leaking: UNKNOWN
│    Retaining 12.4 kB in 434 objects
│    ↓ MapboxTripNotification.notificationProvider
│                             ~~~~~~~~~~~~~~~~~~~~
├─ xxx.xxx.ably.PublisherService$createPublisher$6 instance
│    Leaking: UNKNOWN
│    Retaining 12.3 kB in 433 objects
│    Anonymous class implementing com.ably.tracking.publisher.
│    PublisherNotificationProvider
│    this$0 instance of xxx.xxx.ably.PublisherService
│    ↓ PublisherService$createPublisher$6.this$0
│                                         ~~~~~~
╰→ xxx.xxx.ably.PublisherService instance
     Leaking: YES (ObjectWatcher was watching this because xxx.xxx.ably.PublisherService 
     received Service#onDestroy() callback and Service not held by ActivityThread)
     Retaining 12.3 kB in 432 objects
     watchDurationMillis = 29325
     retainedDurationMillis = 23891
```

### LINKED ISSUE #815: Fix memory leaks on publisher example apps
I realized that when using publisher example app, [Leak Canary](https://square.github.io/leakcanary/) raises an important amount of memory leaks. 
An example 

```
GC Root: Input or output parameters in native code
│
├─ io.ably.lib.transport.ConnectionManager instance
│    Leaking: UNKNOWN
│    Retaining 529.4 kB in 9551 objects
│    ↓ ConnectionManager.channels
│                        ~~~~~~~~
├─ io.ably.lib.realtime.AblyRealtime$InternalChannels instance
│    Leaking: UNKNOWN
│    Retaining 526.9 kB in 9466 objects
│    ↓ InternalMap.map
│                  ~~~
├─ java.util.concurrent.ConcurrentHashMap instance
│    Leaking: UNKNOWN
│    Retaining 526.9 kB in 9465 objects
│    ↓ ConcurrentHashMap["tracking:two"]
│                       ~~~~~~~~~~~~~~~~
├─ io.ably.lib.realtime.Channel instance
│    Leaking: UNKNOWN
│    Retaining 240.5 kB in 4655 objects
│    ↓ EventEmitter.listeners
│                   ~~~~~~~~~
├─ java.util.ArrayList instance
│    Leaking: UNKNOWN
│    Retaining 238.9 kB in 4609 objects
│    ↓ ArrayList[0]
│               ~~~
├─ com.ably.tracking.common.DefaultAbly$$ExternalSyntheticLambda2 instance
│    Leaking: UNKNOWN
│    Retaining 238.8 kB in 4607 objects
│    ↓ DefaultAbly$$ExternalSyntheticLambda2.f$0
│                                            ~~~
├─ com.ably.tracking.publisher.workerqueue.workers.
│  ConnectionReadyWorker$subscribeForChannelStateChanges$1 instance
│    Leaking: UNKNOWN
│    Retaining 238.8 kB in 4606 objects
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ ConnectionReadyWorker$subscribeForChannelStateChanges$1.this$0
│                                                              ~~~~~~
├─ com.ably.tracking.publisher.workerqueue.workers.ConnectionReadyWorker
│  instance
│    Leaking: UNKNOWN
│    Retaining 238.8 kB in 4605 objects
│    ↓ ConnectionReadyWorker.callbackFunction
│                            ~~~~~~~~~~~~~~~~
├─ com.ably.tracking.publisher.DefaultCorePublisher$trackTrackable$1 instance
│    Leaking: UNKNOWN
│    Retaining 238.7 kB in 4603 objects
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ DefaultCorePublisher$trackTrackable$1.$callbackFunction
│                                            ~~~~~~~~~~~~~~~~~
├─ com.ably.tracking.common.CallbackFunctionModelsKt$wrapInResultCallback$1
│  instance
│    Leaking: UNKNOWN
│    Retaining 238.7 kB in 4602 objects
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ CallbackFunctionModelsKt$wrapInResultCallback$1.
│    $this_wrapInResultCallback
│    ~~~~~~~~~~~~~~~~~~~~~~~~~~
├─ kotlin.coroutines.SafeContinuation instance
│    Leaking: UNKNOWN
│    Retaining 238.7 kB in 4601 objects
│    ↓ SafeContinuation.delegate
│                       ~~~~~~~~
├─ kotlinx.coroutines.internal.DispatchedContinuation instance
│    Leaking: UNKNOWN
│    Retaining 238.7 kB in 4600 objects
│    ↓ DispatchedContinuation.continuation
│                             ~~~~~~~~~~~~
├─ com.ably.tracking.example.publisher.
│  AddTrackableActivity$addTrackableClicked$1$1$2 instance
│    Leaking: UNKNOWN
│    Retaining 238.6 kB in 4599 objects
│    Anonymous subclass of kotlin.coroutines.jvm.internal.SuspendLambda
│    $publisherService instance of com.ably.tracking.example.publisher.
│    PublisherService
│    this$0 instance of com.ably.tracking.example.publisher.
│    AddTrackableActivity with mDestroyed = true
│    ↓ AddTrackableActivity$addTrackableClicked$1$1$2.this$0
│                                                     ~~~~~~
╰→ com.ably.tracking.example.publisher.AddTrackableActivity instance
​     Leaking: YES (ObjectWatcher was watching this because com.ably.tracking.
​     example.publisher.AddTrackableActivity received Activity#onDestroy()
​     callback and Activity#mDestroyed is true)
​     Retaining 238.5 kB in 4594 objects
​     key = a28836fb-990e-4f34-be44-f551930f9c17
​     watchDurationMillis = 7488
​     retainedDurationMillis = 2487
​     mApplication instance of com.ably.tracking.example.publisher.
​     PublishingExampleApplication
​     mBase instance of androidx.appcompat.view.ContextThemeWrapper
METADATA
Build.VERSION.SDK_INT: 33
Build.MANUFACTURER: Google
LeakCanary version: 2.10
App process name: com.ably.tracking.example.publisher
Class count: 28693
Instance count: 1708946
Primitive array count: 320654
Object array count: 97576
Thread count: 64
Heap total bytes: 90901246
Bitmap count: 7
Bitmap total bytes: 104891
Large bitmap count: 0
Large bitmap total bytes: 0
Db 1: open /data/user/0/com.ably.tracking.example.publisher/no_backup/androidx.
work.workdb
Db 2: open /data/user/0/com.ably.tracking.example.
publisher/databases/awss3transfertable.db
Stats: LruCache[maxSize=3000,hits=122288,misses=310923,hitRate=28%]
RandomAccess[bytes=16090421,reads=310923,travel=488453745872,range=103683711,siz
e=134585752]
Analysis duration: 21193 ms
```

I will attach others captured as file attachments

### PR DESCRIPTION
**Pull request by ikbalkaya**
This is a fix for https://github.com/ably/ably-asset-tracking-android/issues/810

- Wraps the android context in a weak reference, so that is not kept after the service is destroyed
- Unsets the static mapbox notification provider when DefaultMapbox destroys MapboxNavigation
- Tidies up references to the PublisherService and various coroutines when it is shut down
- Passes a clone of the publisher service's notification to mapbox to prevent it keeping the service in scope when the publisher is shutdown (this has been raised with mapbox separately)
- Removes all ably connection listeners when the connection is shut down, to avoid the service leaking through these
- Removes all the ably channel state listeners when a channel state is disconnected, prior to being released, to work around an ably-java issue that leaks them

Closes #810 
Closes #815

### CODE REVIEW

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt [hunk 1]
```diff
@@ -11,11 +11,12 @@ import com.ably.tracking.common.logging.createLoggingTag
 import com.ably.tracking.common.logging.v
 import com.ably.tracking.connection.ConnectionConfiguration
 import com.ably.tracking.logging.LogHandler
+import java.lang.ref.WeakReference
 
 internal data class PublisherBuilder(
     val connectionConfiguration: ConnectionConfiguration? = null,
     val mapConfiguration: MapConfiguration? = null,
-    val androidContext: Context? = null,
+    val androidContext: WeakReference<Context>? = null,
```
Comment (davyskiba) [inline publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt:19]: I think this change is not necessary, as we're passing a strong reference to Mapbox anyway 🤔

File: publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt [hunk 2]
```diff
@@ -61,15 +63,16 @@ class PublisherService : Service() {
         return START_NOT_STICKY
     }
 
-    inner class Binder : android.os.Binder() {
-        fun getService(): PublisherService = this@PublisherService
+    inner class Binder(private val weakService: WeakReference<PublisherService>) : android.os.Binder() {
```
Comment (davyskiba) [inline publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt:66]: As stated [in the kotlin doc](https://kotlinlang.org/docs/nested-classes.html#inner-classes), inner classes strongly reference outer classes as a language feature. To break this connection, we need to remove inner keyword on Binder class

**Review by davyskiba — CHANGES_REQUESTED** [review]

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt (hunk 1 above)
Comment (ikbalkaya) [reply publishing-sdk/src/main/java/com/ably/tracking/publisher/PublisherBuilder.kt:19]: I think you are right here - In this case I suppose the issue stays with Mapbox. I will ping them 👍

File: publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt (hunk 2 above)
Comment (ikbalkaya) [reply publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt]: This is no longer an inner class 9e03c14b39f0da189bbf48587dfa7cdade967541

**Review by KacperKluka — CHANGES_REQUESTED** [review]
Looks good, just a few suggestions 😉

File: publishing-example-app/build.gradle [hunk 3]
```diff
@@ -30,6 +30,9 @@ dependencies {
     implementation 'pub.devrel:easypermissions:3.0.0'
     // This version needs to be compatible with the "com.mapbox.navigation:core" dependency version from publishing-sdk.
     implementation 'com.mapbox.maps:android:10.8.0'
+    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.5.1'
+    //for memory leak detection
+    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.10'
```
Comment (davyskiba) [inline publishing-example-app/build.gradle:35]: Since this is so easy to add, maybe it is worth adding to the subscriber example too?

File: publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt [hunk 4]
```diff
@@ -61,15 +63,16 @@ class PublisherService : Service() {
...
+    class Binder(private val weakService: WeakReference<PublisherService>) : android.os.Binder() {
+        fun getService(): PublisherService? = weakService.get()
     }
 
     override fun onBind(intent: Intent?): IBinder = binder
 
     override fun onDestroy() {
         // We want to be sure that after the service is stopped the publisher is stopped too.
         // Otherwise we could end up with multiple active publishers.
+        Log.d("onDestroy", "onDestroy: ")
```
[the remark this answers is not in the document]
Comment (AndyTWF) [reply publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt]: Have done this

File: publishing-example-app/build.gradle (hunk 3 above)
Comment (AndyTWF) [reply publishing-example-app/build.gradle:30]: Done this

File: common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt [hunk 5]
```diff
@@ -323,6 +330,13 @@ class DefaultAblyTestEnvironment private constructor(
             every { channelMock.off(any()) } returns Unit
         }
 
+        /**
+         * Stubs [channelMock]’s [AblySdkRealtime.Channel.off] method (the overload with no listeners).
+         */
+        fun stubOffAll() {
```
Comment (davyskiba) [inline common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt:336]: Do we need both `stubOffAll` and `stubOffNoListeners`?

File: common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt [hunk 6]
```diff
@@ -513,12 +527,19 @@ class DefaultAblyTestEnvironment private constructor(
     }
 
     /**
-     * Stubs [connectionMock]’s [AblySdkRealtime.Connection.off] method.
+     * Stubs [connectionMock]’s [AblySdkRealtime.Connection.off] method (the override with a single listener).
      */
     fun stubConnectionOff() {
```
Comment (davyskiba) [inline common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt:532]: Do we need control over which overload is stubbed? In some other part we've been mocking all under in function

File: common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt (hunk 5 above)
Comment (AndyTWF) [reply common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt:336]: Removed the latter!

File: common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt [hunk 7]
```diff
@@ -1012,6 +1013,7 @@ class DefaultAblyTestScenarios {
                          * ...and calls `get` on the Channels instance...
                          * ...and tells the channel to leave presence...
                          * ...and calls `unsubscribe` on the channel and on its Presence instance...
+                         * ...and calls `off` on the channel to unregister all listeners
```
Comment (lawrence-forooghian) [inline common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt:1016]: Please can you propagate this prose description to the docstring for this method and subsequently to the prose comments in the test methods that call this method?

Comment (AndyTWF) [reply common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestScenarios.kt]: Yes done :) d945ec50

File: common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt (hunk 6 above)
Comment (AndyTWF) [reply common/src/test/java/com/ably/tracking/common/helper/DefaultAblyTestEnvironment.kt]: Done :)

**Review by davyskiba — APPROVED** [review]

**Review by lawrence-forooghian — APPROVED** [review]

File: common/src/main/java/com/ably/tracking/common/Ably.kt [hunk 8]
```diff
@@ -1049,12 +1051,15 @@ constructor(
...
             }
+            ably.connection.off()
             Result.success(Unit)
         } catch (connectionException: ConnectionException) {
             logHandler?.w("$TAG Failed to stop Ably connection", connectionException)
+            ably.connection.off()
             Result.failure(connectionException)
         } catch (exception: TimeoutCancellationException) {
             logHandler?.w("$TAG Stop Ably connection timed out", exception)
+            ably.connection.off()
```
Comment (kozaxinan) [inline common/src/main/java/com/ably/tracking/common/Ably.kt:1062]: This can be handled in finally block.

File: publishing-sdk/src/main/java/com/ably/tracking/publisher/BatteryDataProvider.kt [hunk 9]
```diff
@@ -20,12 +21,15 @@ internal interface BatteryDataProvider {
 /**
  * Based on https://developer.android.com/training/monitoring-device-state/battery-monitoring
  */
-internal class DefaultBatteryDataProvider(private val context: Context) : BatteryDataProvider {
+internal class DefaultBatteryDataProvider(context: Context) : BatteryDataProvider {
```
Comment (kozaxinan) [inline publishing-sdk/src/main/java/com/ably/tracking/publisher/BatteryDataProvider.kt:24]: why is this provider is in use after the context is destroyed? would be easier to stop using old battery provider and just create a new one with new context?
this weak reference could create buggy scenarios after context is destroyed and cleaned up. wdyt?
